customhost = "database-1.cozsdhyiskuj.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "wongjetsheng-employee"
customregion = "us-east-1"
